--pid option is type integer.
Fixes this error when sslsniff is used with --pid option:

ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: wrong type